classdef EP_Feedback
    enumeration
        FEEDBACK_OK,
        FEEDBACK_PROCEEDING,
        FEEDBACK_ERROR_INVALID_ID,
        FEEDBACK_ERROR_NULLPTR,
        FEEDBACK_ERROR_NOT_INITIALIZED,
        FEEDBACK_ERROR_LENGTH,
        FEEDBACK_ERROR_BUFFER_OVERFLOW,
        FEEDBACK_ERROR_WRONG_PACKET,
        FEEDBACK_ERROR_CRC,
        FEEDBACK_ERROR_NOT_ENOUGH_BUFFER_SIZE
    end
end

