classdef EP_PacketState
    enumeration
        PACKET_PARSING_STATE_IDLE
        PACKET_PARSING_STATE_RESERVED
        PACKET_PARSING_STATE_ID
        PACKET_PARSING_STATE_LENGTH_L
        PACKET_PARSING_STATE_LENGTH_H
        PACKET_PARSING_STATE_INST
        PACKET_PARSING_STATE_DATA
        PACKET_PARSING_STATE_CRC_L
        PACKET_PARSING_STATE_CRC_H
    end
end

